Repository fossasia/badgemagic-app, pull requests merged in 2019-12, with the labels that each got.

#543 fix: privacy storage access crash
  app/src/main/AndroidManifest.xml
Labels: fix

#538 feat: added shortcut to open saved activities from edit activities
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/EditBadgeActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/EditClipartActivity.kt
  app/src/main/res/drawable/ic_folder_open_black_24dp.xml
  app/src/main/res/menu/open_folder.xml
Labels: feature

#534 feat: share app details on social platforms
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/menu/drawer_items.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#547 chore: update build number for release 1.6.0
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/8.txt
Labels: chore

#553 fix: Release aab path
  fastlane/Fastfile
Labels: fix

#557 chore: fail script when deployment not successful
  scripts/upload-apk.sh
Labels: chore

#559 feat: app specific directory storage
  app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt
  app/src/main/java/org/fossasia/badgemagic/database/StorageFilesService.kt
  app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/EditBadgeActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/EditClipartActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/DrawFragment.kt
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
Labels: feature

#562 chore: improve storage utils and remove requestLegacyStorage
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
Labels: chore

#563 fix: support non latin languages
  app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
Labels: fix

#568 fix: Resolve delete cliparts issue
  app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt
  app/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt
Labels: fix

#572 feat: Improve AboutUs
  app/src/main/res/layout/fragment_about_us.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#570 fix: reverse listing of saved badges
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
Labels: fix

#576 fix: Resolve intermediate clipart delete issue
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
Labels: fix

#578 fix: uneven clipart listing
  app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
Labels: fix

#582 fix: Update latest UI screenshots in Readme
  docs/images/screen-1.png
  docs/images/screen-2.png
  docs/images/screen-3.png
  docs/images/screen-4.png
  docs/images/screen-5.png
  docs/images/screen-6.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-6.png
Labels: fix

#587 fix: Resolve keyboard visibility issue
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
Labels: fix

#567 fix: Improve drawer header #564
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_header_background.xml
  app/src/main/res/font/open_sans_semibold.xml
  app/src/main/res/layout/nav_header_drawer.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
Labels: fix

#585 feat: feature to turn bluetooth on
  app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
  app/src/main/java/org/fossasia/badgemagic/util/BluetoothAdapter.kt
Labels: feature

#593 chore: refactor StorageUtils
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
Labels: chore

#596 feat: Add AlertWarning for deleting badges and cliparts
  app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
  app/src/main/res/drawable/ic_delete_black_24dp.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#597 fix: Resolve drawer selection issue in draw clipart fragment
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
Labels: fix
