Repository fossasia/badgemagic-app, pull requests merged in 2019-07, with the labels that each got.

#424 fix: indexOutOfBounds exception in drawlayout
  app/src/main/java/org/fossasia/badgemagic/ui/custom/DrawBadgeLayout.kt
Labels: fix

#422 chore: Improve APK Names
  scripts/prep-key.sh
  scripts/upload-apk.sh
Labels: chore

#428 chore: added aab support and improved script
  .travis.yml
  app/build.gradle
  build.gradle
  scripts/upload-apk.sh
Labels: chore

#432 fix: Use correct AAB and APK filenames
  scripts/upload-apk.sh
Labels: fix

#433 chore: update upload script
  scripts/upload-apk.sh
Labels: chore

#434 chore: Release v1.3.0
  .travis.yml
  README.md
  app/build.gradle
  app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt
  app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsViewHolder.kt
  app/src/main/java/org/fossasia/badgemagic/bindings/SavedClipartsViewBindings.kt
  app/src/main/java/org/fossasia/badgemagic/data/SavedClipart.kt
  app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt
  app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/custom/DrawBadgeLayout.kt
  app/src/main/java/org/fossasia/badgemagic/ui/custom/SquareImageView.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedClipartFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
  app/src/main/java/org/fossasia/badgemagic/util/ImageUtils.kt
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
  app/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt
  app/src/main/res/drawable/ic_draw_delete.xml
  app/src/main/res/layout/fragment_saved_cliparts.xml
  app/src/main/res/layout/recycler_item_saved_clipart.xml
  app/src/main/res/menu/drawer_items.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-6.png
  scripts/prep-key.sh
  scripts/upload-apk.sh
Labels: chore

#437 chore: Baseline master into dev
  scripts/upload-apk.sh
Labels: chore

#440 fix: retain fragment info when orientation changed
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
Labels: fix

#448 fix: travis build
  .travis.yml
Labels: fix

#447 build(deps): updated kotlin version
  versions.gradle
Labels: dependencies

#444 fix: invert LED bug
  app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
Labels: fix

#452 chore: updated build version to 1.4.0
  app/build.gradle
Labels: chore

#456 chore: Add fastlane metadata
  .travis.yml
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/metadata/android/en-US/changelogs/1.txt
  fastlane/metadata/android/en-US/changelogs/2.txt
  fastlane/metadata/android/en-US/changelogs/3.txt
  fastlane/metadata/android/en-US/changelogs/4.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/images/sevenInchScreenshots/.gitkeep
  fastlane/metadata/android/en-US/images/tenInchScreenshots/.gitkeep
  fastlane/metadata/android/en-US/images/tvScreenshots/.gitkeep
  fastlane/metadata/android/en-US/images/wearScreenshots/.gitkeep
  fastlane/metadata/android/en-US/short_description.txt
  fastlane/metadata/android/en-US/title.txt
  fastlane/metadata/android/en-US/video.txt
  scripts/.gitignore
Labels: chore

#457 chore: improved fastlane usage and scripts
  .travis.yml
  Gemfile
  fastlane/Fastfile
  scripts/upload-apk.sh
Labels: chore
