Repository fossasia/badgemagic-app, pull requests merged in 2019-06, with the labels that each got.

#344 fix: Do not show emoticons always
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
  app/src/main/java/org/fossasia/badgemagic/viewmodels/TextArtViewModel.kt
  app/src/main/res/drawable/ic_clipart.xml
  app/src/main/res/layout-land/fragment_main_textart.xml
  app/src/main/res/layout/fragment_main_textart.xml
Labels: fix

#340 chore: Updated README with FDroid Badge
  README.md
  docs/images/app_icon.png
  docs/images/app_icon.svg
Labels: chore

#349 fix: NULLPointerException , when characterstics is null
  app/src/main/java/org/fossasia/badgemagic/data/device/bluetooth/GattClient.kt
Labels: fix

#350 fix: Issue when edittext is empty and send is clicked
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
  app/src/main/res/values/strings.xml
Labels: fix

#358 feat: Bluetooth permission is asked when user presses the transfer button
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
  app/src/main/res/values/strings.xml
Labels: feature

#359 chore: Replaced context with requireContext
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
Labels: chore

#348 fix: Decrease white space above top buttons, increase space above sav…
  app/src/main/res/layout-land/fragment_main_textart.xml
  app/src/main/res/layout/fragment_main_textart.xml
  app/src/main/res/layout/sections_tab.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml-v25/shortcuts.xml
Labels: fix

#362 docs: Updated fdroid badge
  README.md
  docs/images/fdroid_badge.png
Labels: Documentation

#352 fix: issues and improve Saved Badges screen
  app/src/main/res/drawable/ic_emoji.xml
  app/src/main/res/layout-land/fragment_main_save.xml
  app/src/main/res/layout/fragment_main_save.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: fix

#374 feat: implement drawing layout
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/badgemagic/bindings/DrawViewBindings.kt
  app/src/main/java/org/fossasia/badgemagic/data/draw_layout/DrawMode.kt
  app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
  app/src/main/java/org/fossasia/badgemagic/ui/DrawActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/custom/DrawBadgeLayout.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SettingsFragment.kt
  app/src/main/java/org/fossasia/badgemagic/viewmodels/DrawViewModel.kt
  app/src/main/res/drawable/ic_draw_erase.xml
  app/src/main/res/drawable/ic_draw_pencil.xml
  app/src/main/res/drawable/ic_draw_reset.xml
  app/src/main/res/layout/activity_draw.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle.properties
  versions.gradle
Labels: feature

#371 fix: Morphing Issues with Preview Badge
  app/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
Labels: fix

#377 feat: multilanguage support
  app/build.gradle
  app/src/main/java/org/fossasia/badgemagic/BadgeMagicApp.kt
  app/src/main/java/org/fossasia/badgemagic/bindings/SettingsViewBindings.kt
  app/src/main/java/org/fossasia/badgemagic/data/Language.kt
  app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt
  app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/base/BaseActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/base/BaseFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/AboutFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SettingsFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
  app/src/main/java/org/fossasia/badgemagic/util/LocaleManager.kt
  app/src/main/java/org/fossasia/badgemagic/util/PreferenceUtils.kt
  app/src/main/java/org/fossasia/badgemagic/util/Resource.kt
  app/src/main/java/org/fossasia/badgemagic/viewmodels/SettingsViewModel.kt
  app/src/main/res/drawable/ic_menu_settings.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/menu/drawer_items.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#378 chore: Updated Screenshots
  docs/images/screen-1.png
  docs/images/screen-2.png
  docs/images/screen-3.png
  docs/images/screen-4-hard.png
  docs/images/screen-4.png
  docs/images/screen-5.png
  docs/images/screen-6-hard.png
  docs/images/screen-6.png
Labels: chore

#367 fix: Only allow oneliners
  app/src/main/res/layout-land/fragment_main_textart.xml
  app/src/main/res/layout/fragment_main_textart.xml
Labels: fix

#379 chore: Release v1.2.0
  app/build.gradle
Labels: chore

#381 chore: correct build version from 1.2.0 to 1.1.0
  app/build.gradle
Labels: chore

#382 feat: option to edit badges
  app/src/main/java/org/fossasia/badgemagic/adapter/SaveAdapter.kt
  app/src/main/java/org/fossasia/badgemagic/bindings/DrawViewBindings.kt
  app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
  app/src/main/java/org/fossasia/badgemagic/ui/DrawActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/custom/DrawBadgeLayout.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
  app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
  app/src/main/java/org/fossasia/badgemagic/viewmodels/DrawViewModel.kt
  app/src/main/res/drawable/ic_draw_pencil.xml
  app/src/main/res/drawable/ic_draw_save.xml
  app/src/main/res/drawable/ic_play_pause.xml
  app/src/main/res/layout-land/recycler_save_item.xml
  app/src/main/res/layout/activity_draw.xml
  app/src/main/res/layout/recycler_save_item.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#395 fix: badge seems to cut off on devices with 19.5:9 ratio
  app/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
Labels: fix

#397 chore: translate strings to chinese for next release
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: chore

#400 chore: updated build version to 1.2.0
  app/build.gradle
Labels: chore

#399 chore: remove before-install script
  .travis.yml
Labels: chore

#408 feat: ability to show badges
  app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt
  app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsViewHolder.kt
  app/src/main/java/org/fossasia/badgemagic/bindings/SavedClipartsViewBindings.kt
  app/src/main/java/org/fossasia/badgemagic/data/SavedClipart.kt
  app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt
  app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/custom/SquareImageView.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedClipartFragment.kt
  app/src/main/java/org/fossasia/badgemagic/util/ImageUtils.kt
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
  app/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt
  app/src/main/res/drawable/ic_draw_delete.xml
  app/src/main/res/layout/fragment_saved_cliparts.xml
  app/src/main/res/layout/recycler_item_saved_clipart.xml
  app/src/main/res/menu/drawer_items.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#412 feat: Added toast when a badge is saved
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#415 fix: Prevented bluetooth form closing automatically when drawer activity is destroyed.
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
Labels: fix

#418 fix: force stop when rejected permission
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
Labels: fix

#419 feat: ability to delete cliparts
  app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt
  app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsViewHolder.kt
  app/src/main/java/org/fossasia/badgemagic/ui/custom/SquareImageView.kt
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
  app/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt
  app/src/main/res/layout/recycler_item_saved_clipart.xml
Labels: feature

#417 feat: fdroid screenshots
  README.md
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-6.png
Labels: feature
