Repository fossasia/badgemagic-app, pull requests merged in 2019-04, with the labels that each got.

#161 fix: typo in bundle key
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Labels: fix

#145 chore: add contribution guidelines
  CONTRIBUTING.md
  README.md
  docs/commitStyle.md
Labels: Documentation, chore

#162 fix: Enabling both chekbox at a same time
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
Labels: fix

#173 chore: refractor drawable adapter
  app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt
Labels: chore, refactor

#174 feat: app can be used without bluetooth
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
  app/src/main/res/values/strings.xml
Labels: feature

#167 fix: scan logic
  app/src/main/java/com/nilhcem/blenamebadge/device/bluetooth/ScanHelper.kt
Labels: fix

#177 feat: Animation Mode in Preview
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Labels: feature

#180 feat : Added Laser Animation and made conditions more readable
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Labels: feature

#179 fix: animations go on the wrong side of the screen
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Labels: fix

#178 fix: multiple bluetooth dialogs on rotation
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
Labels: fix

#181 feat: Radio buttons for text and drawable.
  app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
  app/src/main/res/layout/message_activity.xml
  app/src/main/res/values/strings.xml
Labels: feature

#183 feat: added core changes to send drawable to actual device
  app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/model/BitmapDataToSend.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/model/BitmapMessage.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt
Labels: feature

#185 fix: spinners and checkbox now trigger automatic preview
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
Labels: fix

#187 feat: Inverted LED Effect
  app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/model/DataToSend.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/Converters.kt
  app/src/main/res/layout/message_activity.xml
  app/src/main/res/values/strings.xml
Labels: feature

#190 chore: migrated to android jetpack
  app/build.gradle
  app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/model/Mode.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/Converters.kt
  app/src/main/res/layout/message_activity.xml
  app/src/main/res/layout/recycler_item.xml
  build.gradle
Labels: chore

#191 fix: Made keyboard appear automatically when shifting to text mode.
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/KeyboardUtils.kt
Labels: fix

#195 refactor: single code base for both text and drawables & other bug fixes
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nilhcem/blenamebadge/core/android/ext/ViewExt.kt
  app/src/main/java/com/nilhcem/blenamebadge/core/android/viewbinding/Kotterknife.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/bluetooth/GattClient.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/bluetooth/ScanHelper.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/model/BitmapDataToSend.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/model/BitmapMessage.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/model/DataToSend.kt
  app/src/main/java/com/nilhcem/blenamebadge/device/model/Message.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/Converters.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/KeyboardUtils.kt
  app/src/main/res/layout/message_activity.xml
  app/src/main/res/layout/recycler_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/nilhcem/blenamebadge/SampleTest.kt
  app/src/test/java/com/nilhcem/blenamebadge/core/utils/ByteArrayUtilsTest.kt
  app/src/test/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverterTest.kt
Labels: refactor

#196 chore: Add Launcher Icon
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-web.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  ic_web.svg
Labels: chore

#194 chore(docs): Added screenshots of the latest UI to the readme.
  README.md
  docs/images/badge-magic-screenshot.jpg
Labels: Documentation

#201 fix: Loader will be displayed on clicking send.
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
Labels: fix

#202 feat: Add Snowflake Animation Mode
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Labels: feature

#204 feat: save, export and import badge options
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt
  app/src/main/java/com/nilhcem/blenamebadge/adapter/MainPagerAdapter.kt
  app/src/main/java/com/nilhcem/blenamebadge/adapter/SaveAdapter.kt
  app/src/main/java/com/nilhcem/blenamebadge/core/android/viewbinding/Kotterknife.kt
  app/src/main/java/com/nilhcem/blenamebadge/data/BadgeConfig.kt
  app/src/main/java/com/nilhcem/blenamebadge/data/ConfigInfo.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/BaseFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/MainSavedFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/MainTextDrawableFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/interfaces/PreviewChangeListener.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainPresenter.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/Converters.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/MoshiUtils.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/StorageUtils.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_chip_flash.xml
  app/src/main/res/drawable/ic_chip_inverted.xml
  app/src/main/res/drawable/ic_chip_marquee.xml
  app/src/main/res/drawable/ic_chip_speed.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_save.xml
  app/src/main/res/layout/fragment_main_save.xml
  app/src/main/res/layout/fragment_main_text.xml
  app/src/main/res/layout/recycler_save_item.xml
  app/src/main/res/menu/save_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/file_provider_paths.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#213 feat: Sending Animation for FAB Button
  app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt
  app/src/main/res/layout-land/message_activity.xml
  app/src/main/res/values/strings.xml
Labels: feature

#218 feat: Bottombar for navigation between fragments
  app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt
  app/src/main/res/color/navigation_item.xml
  app/src/main/res/drawable/ic_bottom_bar_saved.xml
  app/src/main/res/drawable/ic_bottom_bar_text.xml
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#221 feat: Added 8 new symbols
  app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt
Labels: feature

#212 fix: Avoid app crash on saving after screen rotation
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/MainSavedFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/MainTextDrawableFragment.kt
  app/src/main/res/layout/fragment_main_save.xml
  app/src/main/res/layout/fragment_main_text.xml
Labels: fix

#217 fix: If the selected item is deleted, preview is cleared and a toast is displayed
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/MainSavedFragment.kt
  app/src/main/res/values/strings.xml
Labels: fix

#210 feat: Add horizontal variations
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
  app/src/main/res/layout-land/fragment_main_text.xml
  app/src/main/res/layout-land/recycler_save_item.xml
  app/src/main/res/layout/dialog_save.xml
  app/src/main/res/layout/fragment_main_save.xml
  app/src/main/res/layout/fragment_main_text.xml
  app/src/main/res/layout/recycler_item.xml
  app/src/main/res/layout/recycler_save_item.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#225 fix: app crash on rotation
  app/src/main/res/layout-land/fragment_main_text.xml
Labels: fix

#223 fix: viewpager not initializing when bluetooth not enabled
  app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt
Labels: fix

#226 feat: Added more symbols.
  app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt
Labels: feature

#228 feat: Picture Animation Mode
  app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Labels: feature
