Repository fossasia/badgemagic-app, pull requests merged in 2019-05, with the labels that each got.

#229 fix: Keyboard goes down when shifting to saved mode.
  app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt
Labels: fix

#243 fix: added a transfer button on the right of send button
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainNavigator.kt
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout-land/fragment_main_text.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_main_text.xml
  app/src/main/res/values/strings.xml
Labels: fix

#244 feat: Change "Mode" to visual interpretation
  .travis.yml
  app/build.gradle
  app/src/main/java/com/nilhcem/blenamebadge/adapter/ModeAdapter.kt
  app/src/main/java/com/nilhcem/blenamebadge/data/ModeInfo.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableNavigator.kt
  app/src/main/res/drawable-anydpi/ic_anim_animation.gif
  app/src/main/res/drawable-anydpi/ic_anim_down.gif
  app/src/main/res/drawable-anydpi/ic_anim_fixed.gif
  app/src/main/res/drawable-anydpi/ic_anim_laser.gif
  app/src/main/res/drawable-anydpi/ic_anim_left.gif
  app/src/main/res/drawable-anydpi/ic_anim_picture.gif
  app/src/main/res/drawable-anydpi/ic_anim_right.gif
  app/src/main/res/drawable-anydpi/ic_anim_up.gif
  app/src/main/res/layout-land/fragment_main_text.xml
  app/src/main/res/layout/fragment_main_text.xml
  app/src/main/res/layout/recycler_item_mode.xml
  app/src/main/res/values/strings.xml
Labels: feature

#246 feat: Implement "Effects" in same way as "Animations"
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt
  app/src/main/res/drawable-anydpi/ic_effect_flash.gif
  app/src/main/res/drawable-anydpi/ic_effect_invert.gif
  app/src/main/res/drawable-anydpi/ic_effect_marquee.gif
  app/src/main/res/layout-land/fragment_main_text.xml
  app/src/main/res/layout/effects_layout.xml
  app/src/main/res/layout/fragment_main_text.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#247 feat: Implement "Speed Wheel"
  app/src/main/java/com/nilhcem/blenamebadge/ui/custom/knob/Croller.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/custom/knob/OnCrollerChangeListener.java
  app/src/main/java/com/nilhcem/blenamebadge/ui/custom/knob/utilities/Utils.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout-land/fragment_main_text.xml
  app/src/main/res/layout/fragment_main_text.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/croller_attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/integers.xml
  settings.gradle
Labels: feature

#147 fix: Retain app state on screen rotation
  app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt
  app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableItemHolder.kt
  app/src/main/java/com/nilhcem/blenamebadge/adapter/ModeAdapter.kt
  app/src/main/java/com/nilhcem/blenamebadge/adapter/ModeItemHolder.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/App.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableNavigator.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableViewModel.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/Resource.kt
Labels: fix

#260 feat : Implement Clipart (Drawables) dropdown area
  app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableItemHolder.kt
  app/src/main/java/com/nilhcem/blenamebadge/adapter/ModeItemHolder.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt
  app/src/main/res/drawable/round_corner_bg.xml
  app/src/main/res/layout-land/fragment_main_text.xml
  app/src/main/res/layout/fragment_main_text.xml
  app/src/main/res/layout/recycler_item.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#274 chore: Updated screenshots in the README.md.
  README.md
Labels: chore

#273 refactor: Remove useless interfaces, matche MVVM architecture
  app/src/main/java/com/nilhcem/blenamebadge/ui/AppViewModel.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/drawer/DrawerActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/drawer/DrawerNavigator.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/base/BaseFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_saved/MainSavedFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_saved/MainSavedNavigator.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableViewModel.kt
Labels: refactor

#276 fix: Prevented app from crashing when opened.
  app/src/main/java/com/nilhcem/blenamebadge/ui/drawer/DrawerActivity.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_saved/MainSavedFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableViewModelProviderFactory.kt
  app/src/main/java/com/nilhcem/blenamebadge/util/InjectorUtils.kt
Labels: fix

#279 fix: Memory Leak
  app/src/main/java/com/nilhcem/blenamebadge/ui/custom/PreviewBadge.kt
Labels: fix

#281 fix: retain items on rotate
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_saved/MainSavedFragment.kt
  app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt
Labels: fix

#286 fix: disable bluetooth when closing app
  app/src/main/java/com/nilhcem/blenamebadge/ui/drawer/DrawerActivity.kt
Labels: fix

#295 fix: reduce size
  app/build.gradle
  app/src/main/res/drawable-anydpi/ic_anim_animation.gif
  app/src/main/res/drawable-anydpi/ic_anim_down.gif
  app/src/main/res/drawable-anydpi/ic_anim_fixed.gif
  app/src/main/res/drawable-anydpi/ic_anim_laser.gif
  app/src/main/res/drawable-anydpi/ic_anim_left.gif
  app/src/main/res/drawable-anydpi/ic_anim_picture.gif
  app/src/main/res/drawable-anydpi/ic_anim_right.gif
  app/src/main/res/drawable-anydpi/ic_anim_up.gif
  app/src/main/res/drawable-anydpi/ic_effect_flash.gif
  app/src/main/res/drawable-anydpi/ic_effect_invert.gif
  app/src/main/res/drawable-anydpi/ic_effect_marquee.gif
Labels: fix

#298 chore: bump gradle versions
  app/build.gradle
  build.gradle
  versions.gradle
Labels: chore

#299 fix: documentation screenshots in docs
  README.md
  docs/images/screen-1-hard.png
  docs/images/screen-1.png
  docs/images/screen-2-hard.png
  docs/images/screen-2.png
  docs/images/screen-3-hard.png
  docs/images/screen-3.png
  docs/images/screen-4-hard.png
  docs/images/screen-4.png
  docs/images/screen-5-hard.png
  docs/images/screen-5.png
  docs/images/screen-6-hard.png
  docs/images/screen-6.png
Labels: fix

#307 chore: Updated spotless kotlin
  app/build.gradle
  app/src/main/java/org/fossasia/badgemagic/ui/AppViewModel.kt
  app/src/main/java/org/fossasia/badgemagic/ui/AppViewModelProviderFactory.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_text/MainTextDrawableViewModelProviderFactory.kt
  app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
Labels: chore

#304 fix: memory leak in fragments
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_saved/MainSavedFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_text/MainTextDrawableFragment.kt
Labels: fix

#309 feat: App shortcuts added
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/badgemagic/ui/drawer/DrawerActivity.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/shortcuts.xml
Labels: feature

#311 fix: memory leak in preview badge
  app/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
Labels: fix

#313 fix: shortcut drawer selected item
  app/src/main/java/org/fossasia/badgemagic/ui/drawer/DrawerActivity.kt
Labels: fix

#322 fix: slow transitions when opening screens
  app/src/main/java/org/fossasia/badgemagic/ui/drawer/DrawerActivity.kt
Labels: fix

#321 chore: update leak canary to alpha 2
  versions.gradle
Labels: chore

#324 fix: converted java file to kotlin
  app/src/main/java/org/fossasia/badgemagic/ui/custom/knob/OnCrollerChangeListener.java
  app/src/main/java/org/fossasia/badgemagic/ui/custom/knob/OnCrollerChangeListener.kt
Labels: fix

#318 fix: moshi adapter issue in release builds
  app/src/main/java/org/fossasia/badgemagic/data/device/model/Mode.kt
  app/src/main/java/org/fossasia/badgemagic/data/device/model/Speed.kt
  app/src/main/java/org/fossasia/badgemagic/util/MoshiUtils.kt
Labels: fix

#326 feat: text and multiple cliparts at the same time
  app/src/main/java/org/fossasia/badgemagic/adapter/DrawableAdapter.kt
  app/src/main/java/org/fossasia/badgemagic/adapter/DrawableItemHolder.kt
  app/src/main/java/org/fossasia/badgemagic/data/DrawableInfo.kt
  app/src/main/java/org/fossasia/badgemagic/data/clipart/ClipArtContainer.kt
  app/src/main/java/org/fossasia/badgemagic/data/clipart/ClipArtDAO.kt
  app/src/main/java/org/fossasia/badgemagic/data/clipart/ClipArtRepository.kt
  app/src/main/java/org/fossasia/badgemagic/data/saved_files/FilesContainer.kt
  app/src/main/java/org/fossasia/badgemagic/data/saved_files/FilesDAO.kt
  app/src/main/java/org/fossasia/badgemagic/data/saved_files/FilesRepository.kt
  app/src/main/java/org/fossasia/badgemagic/data/util/SendingData.kt
  app/src/main/java/org/fossasia/badgemagic/text/CenteredImageSpan.kt
  app/src/main/java/org/fossasia/badgemagic/ui/AppViewModel.kt
  app/src/main/java/org/fossasia/badgemagic/ui/AppViewModelProviderFactory.kt
  app/src/main/java/org/fossasia/badgemagic/ui/drawer/DrawerActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_text/MainTextDrawableViewModelProviderFactory.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_textart/MainTextArtFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_textart/MainTextArtViewModel.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_textart/MainTextArtViewModelProviderFactory.kt
  app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
  app/src/main/java/org/fossasia/badgemagic/util/ImageUtils.kt
  app/src/main/java/org/fossasia/badgemagic/util/InjectorUtils.kt
  app/src/main/java/org/fossasia/badgemagic/util/SendingUtils.kt
  app/src/main/res/drawable/round_corner_bg.xml
  app/src/main/res/layout-land/fragment_main_save.xml
  app/src/main/res/layout-land/fragment_main_textart.xml
  app/src/main/res/layout/fragment_main_save.xml
  app/src/main/res/layout/fragment_main_textart.xml
  app/src/main/res/values/strings.xml
Labels: feature

#330 chore: Add app signing secrets
  scripts/secrets.tar.enc
Labels: chore

#325 chore: automatic signed release
  scripts/prep-key.sh
  scripts/upload-apk.sh
Labels: feature

#332 chore: updated conditions in automatic release scripts
  scripts/prep-key.sh
  scripts/upload-apk.sh
Labels: chore

#329 chore(docs): Added play store badge to readme
  README.md
  docs/images/google_play_badge.png
Labels: Documentation, chore

#333 chore: Baseline master into dev
  scripts/prep-key.sh
  scripts/upload-apk.sh
Labels: chore

#334 chore: Updated Conditions and bumped up minSDK
  scripts/upload-apk.sh
  versions.gradle
Labels: chore

#338 chore: remove deprecated getDrawable method
  app/src/main/java/org/fossasia/badgemagic/adapter/DrawableItemHolder.kt
  app/src/main/java/org/fossasia/badgemagic/adapter/ModeItemHolder.kt
  app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
  app/src/main/java/org/fossasia/badgemagic/util/Resource.kt
Labels: chore
