Repository fossasia/badgemagic-app, pull requests merged in 2020-01, with the labels that each got.

#599 fix: Improve and Fix Saved Badge
  app/src/main/java/org/fossasia/badgemagic/adapter/SaveAdapter.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
  app/src/main/res/drawable/ic_import_export_black_24dp.xml
  app/src/main/res/layout-land/recycler_save_item.xml
  app/src/main/res/layout/recycler_save_item.xml
Labels: fix

#603 fix: location issue with sending badges
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
  app/src/main/java/org/fossasia/badgemagic/util/BluetoothAdapter.kt
Labels: fix

#601 fix: app launch issue
  app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
Labels: fix

#595 feat: multiplatform module for Android and iOS
  .travis.yml
  BadgeMagicModule/build.gradle.kts
  BadgeMagicModule/src/commonMain/kotlin/org/fossasia/badgemagic/data/BadgeConfig.kt
  BadgeMagicModule/src/commonMain/kotlin/org/fossasia/badgemagic/data/ConfigInfo.kt
  BadgeMagicModule/src/commonMain/kotlin/org/fossasia/badgemagic/data/DataToSend.kt
  BadgeMagicModule/src/commonMain/kotlin/org/fossasia/badgemagic/data/Message.kt
  BadgeMagicModule/src/commonMain/kotlin/org/fossasia/badgemagic/data/Mode.kt
  BadgeMagicModule/src/commonMain/kotlin/org/fossasia/badgemagic/data/Speed.kt
  BadgeMagicModule/src/commonMain/kotlin/org/fossasia/badgemagic/device/DataToByteArrayConverter.kt
  BadgeMagicModule/src/commonMain/kotlin/org/fossasia/badgemagic/helpers/JSONHelper.kt
  BadgeMagicModule/src/commonMain/kotlin/org/fossasia/badgemagic/utils/ByteArrayUtils.kt
  README.md
  app/build.gradle
  app/src/main/java/org/fossasia/badgemagic/adapter/SaveAdapter.kt
  app/src/main/java/org/fossasia/badgemagic/bindings/EditBadgeViewBindings.kt
  app/src/main/java/org/fossasia/badgemagic/core/bluetooth/Constants.kt
  app/src/main/java/org/fossasia/badgemagic/core/bluetooth/GattClient.kt
  app/src/main/java/org/fossasia/badgemagic/core/bluetooth/ScanHelper.kt
  app/src/main/java/org/fossasia/badgemagic/data/ModeInfo.kt
  app/src/main/java/org/fossasia/badgemagic/data/device/DataToByteArrayConverter.kt
  app/src/main/java/org/fossasia/badgemagic/data/device/model/DataToSend.kt
  app/src/main/java/org/fossasia/badgemagic/data/device/model/Mode.kt
  app/src/main/java/org/fossasia/badgemagic/data/device/model/Speed.kt
  app/src/main/java/org/fossasia/badgemagic/database/StorageFilesService.kt
  app/src/main/java/org/fossasia/badgemagic/ui/EditBadgeActivity.kt
  app/src/main/java/org/fossasia/badgemagic/ui/base/BaseFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
  app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
  app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
  app/src/main/java/org/fossasia/badgemagic/util/MoshiUtils.kt
  app/src/main/java/org/fossasia/badgemagic/util/SendingUtils.kt
  app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
  build.gradle
  fastlane/metadata/android/en-US/full_description.txt
  scripts/upload-ios-framework.sh
  settings.gradle
  versions.gradle
Labels: WIP, feature

#605 fix: ios-framework build
  .travis.yml
  scripts/upload-ios-framework.sh
Labels: fix

#609 chore: fix upload script with android
  scripts/upload-apk.sh
Labels: chore

#613 chore(deps): bump com.diffplug.gradle.spotless from 3.26.1 to 3.27.0
  android/build.gradle
  build.gradle
Labels: dependencies

#612 fix: ios-framework deploy
  .travis.yml
  BadgeMagicModule/build.gradle.kts
Labels: fix

#615 feat: about us selection in drawer
  android/src/main/res/menu/drawer_items.xml
Labels: feature

#620 fix: Semantic changes for delete confirmation message
  android/src/main/res/values-zh-rCN/strings.xml
  android/src/main/res/values/strings.xml
Labels: fix

#622 feat: Rate application feature so that users can rate app and provide feedback.
  android/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
  android/src/main/res/drawable/ic_star.xml
  android/src/main/res/menu/drawer_items.xml
  android/src/main/res/values-zh-rCN/strings.xml
  android/src/main/res/values/strings.xml
Labels: feature

#627 feat: [Android] allow users to use other badges
  android/src/main/java/org/fossasia/badgemagic/bindings/SettingsViewBindings.kt
  android/src/main/java/org/fossasia/badgemagic/core/bluetooth/Constants.kt
  android/src/main/java/org/fossasia/badgemagic/core/bluetooth/GattClient.kt
  android/src/main/java/org/fossasia/badgemagic/core/bluetooth/ScanHelper.kt
  android/src/main/java/org/fossasia/badgemagic/data/badge/Badges.kt
  android/src/main/java/org/fossasia/badgemagic/data/badge/DeviceID.kt
  android/src/main/java/org/fossasia/badgemagic/di/Modules.kt
  android/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
  android/src/main/java/org/fossasia/badgemagic/ui/EditBadgeActivity.kt
  android/src/main/java/org/fossasia/badgemagic/ui/fragments/SettingsFragment.kt
  android/src/main/java/org/fossasia/badgemagic/util/BadgeUtils.kt
  android/src/main/java/org/fossasia/badgemagic/util/PreferenceUtils.kt
  android/src/main/java/org/fossasia/badgemagic/viewmodels/SettingsViewModel.kt
  android/src/main/res/layout/fragment_settings.xml
  android/src/main/res/values-zh-rCN/strings.xml
  android/src/main/res/values/strings.xml
Labels: feature

#632 feat: Add animation while transition
  android/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
Labels: feature

#640 chore: [iOS] framework builds should be independent
  .gitignore
  .travis.yml
  iOS/badgemagic.xcodeproj/project.pbxproj
Labels: chore
