Repository fossasia/badgemagic-app, pull requests merged in 2020-02, with the labels that each got.

#646 feat: icon when saved clipart or saved list is empty
  android/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
  android/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt
  android/src/main/res/drawable/ic_empty_list.xml
  android/src/main/res/layout-land/fragment_main_save.xml
  android/src/main/res/layout/fragment_main_save.xml
  android/src/main/res/layout/fragment_saved_cliparts.xml
  android/src/main/res/values-land/dimens.xml
  android/src/main/res/values-zh-rCN/strings.xml
  android/src/main/res/values/dimens.xml
  android/src/main/res/values/strings.xml
Labels: feature

#647 fix: app crashes
  android/src/main/java/org/fossasia/badgemagic/ui/fragments/SettingsFragment.kt
  android/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt
Labels: fix

#650 chore: updated version name to 1.7.0
  android/build.gradle
  fastlane/metadata/android/en-US/changelogs/9.txt
Labels: chore

#653 chore: fix fastlane deployment
  fastlane/Fastfile
Labels: chore

#654 chore: updated screenshots for deployment
  README.md
  docs/images/screen-1.jpg
  docs/images/screen-1.png
  docs/images/screen-2.jpg
  docs/images/screen-2.png
  docs/images/screen-3.jpg
  docs/images/screen-3.png
  docs/images/screen-4.jpg
  docs/images/screen-4.png
  docs/images/screen-5.jpg
  docs/images/screen-5.png
  docs/images/screen-6.jpg
  docs/images/screen-6.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-1.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-2.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-3.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-4.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-5.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-6.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-6.png
  scripts/check-screenshots.sh
Labels: chore

#655 chore: updated screenshots for deployment (#654)
  README.md
  docs/images/screen-1.jpg
  docs/images/screen-1.png
  docs/images/screen-2.jpg
  docs/images/screen-2.png
  docs/images/screen-3.jpg
  docs/images/screen-3.png
  docs/images/screen-4.jpg
  docs/images/screen-4.png
  docs/images/screen-5.jpg
  docs/images/screen-5.png
  docs/images/screen-6.jpg
  docs/images/screen-6.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-1.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-2.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-3.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-4.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-5.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-6.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-6.png
  scripts/check-screenshots.sh
Labels: chore

#657 chore: updated screenshot ratio to 2.0 to test deployment
  docs/images/screen-1.jpg
  docs/images/screen-2.jpg
  docs/images/screen-3.jpg
  docs/images/screen-4.jpg
  docs/images/screen-5.jpg
  docs/images/screen-6.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-1.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-2.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-3.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-4.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-5.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screen-6.jpg
Labels: chore

#659 fix: invert LED padding
  android/src/main/java/org/fossasia/badgemagic/util/Converters.kt
Labels: fix

#663 fix: [Android] flash and marquee switched in saved badges
  android/src/main/java/org/fossasia/badgemagic/util/SendingUtils.kt
Labels: fix
